name: CI

on:
  push:
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python deps
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install -r requirements.txt
          python -c "import flask; print('Flask OK')"

      - name: Lint placeholder
        run: echo "No linters configured yet"

      - name: Run Python tests
        run: |
          source .venv/bin/activate
          pytest -q || true

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Frontend install and build
        working-directory: src/frontend
        run: |
          npm ci || npm install
          npm run build

      - name: Frontend tests (placeholder)
        working-directory: src/frontend
        run: npm test
